[package]
name = "reference-kbs"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Lopez <slp@redhat.com>"]
homepage = "https://github.com/virtee/reference-kbs"
license = "Apache-2.0"

[dependencies]
diesel = { version = "1.3", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.3"
hex = "0.4"
kbs-types = { version = "0.4", features = [ "tee-sev", "tee-snp" ] }
libc = "0.2"
rocket = { version = "0.5.0-rc.2", features = [ "json" ] }
rocket_sync_db_pools = { version = "0.1.0-rc.2", features = [ "diesel_sqlite_pool" ] }
serde_json = "1.0"
sev = { version = "1.1.0", features = [ "openssl" ] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
openssl = "0.10.45"
codicon = "3.0.0"
curl = "0.4"
bincode = "1.3"

[patch.crates-io]
sev = { git = "https://github.com/slp/sev", branch = "external-digest", features = [ "openssl"] }
